# Generated automatically from Makefile.in by configure.
SHELL = /bin/sh
#VPATH = /users/u2/ux452875/euler

subdirs = 
top_srcdir = $(HOME)/euler
srcdir = $(HOME)/euler
prefix = $(HOME)/
exec_prefix = $(HOME)
bindir = bin
infodir = $(prefix)/info
libdir = 
mandir = 

#CPPFLAGS = 
#CFLAGS = $(CPPFLAGS) -g -O2
#LDFLAGS = 
#LIBS = -lm 
INSTALL = /usr/local/bin/install -c

CC = gcc
CCOPT = 
LIBS = -lm
INCDIRS = -Iinc/
CFLAGS = ${CCOPT} ${INCDIRS}

PROGRAMS = bl2aln reputer2aln repeat_sin ph2aln longencode repeat_sin_read\
	   simplifygraph simplifygraph_new makefig insencode case2aln\
	   maketxt string2aln string2seq repeat_sin_len simplifygraph_new_len\
	   classifyaln classifyaln_seg grabaln rem_dup rem_hetero prepare_aln put_single\
	   perform_aln count_rep countall cutseq makechrfig makechrrepg segment_cons\
	   def_ancdup loc_core simplifygraph_new_len_new simplifygraph_new_new\
	   pair_bp

all: ${PROGRAMS}

SRCS22 = free_align.c makedge.c readseq1by1.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c repeat_sin_read.c readpar.c\
	erasenext.c initialize.c readposition.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c
OBJS22 = free_align.o makedge.o readseq1by1.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o repeat_sin_read.o readpar.o\
	erasenext.o initialize.o readposition.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o

SRCS21 = free_align.c makedge.c readseq1by1.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c repeat_sin.c readpar.c\
	erasenext.c initialize.c readclass.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c
OBJS21 = free_align.o makedge.o readseq1by1.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o repeat_sin.o readpar.o\
	erasenext.o initialize.o readclass.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o

SRCS25 = free_align.c makedge.c readseq1by1.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c repeat_sin_len.c readpar.c\
	erasenext.c initialize.c readclass.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c\
	readstring.c readreputer.c g_band.c rem_cycle.c
OBJS25 = free_align.o makedge.o readseq1by1.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o repeat_sin_len.o readpar.o\
	erasenext.o initialize.o readclass.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o\
	readstring.o readreputer.o g_band.o rem_cycle.o

SRCS20 = bl2aln.c readblast.c readpar.c random.c\
	 check.c free_align.c
OBJS20 = bl2aln.o readblast.o readpar.o random.o\
	 check.o free_align.o

SRCS10 = longencode.c readblast.c readpar.c random.c char2int.c\
	 check.c free_align.c readclass.c readseq1by1.c trans_loc.c
OBJS10 = longencode.o readblast.o readpar.o random.o char2int.o\
	 check.o free_align.o readclass.o readseq1by1.o trans_loc.o

SRCS11 = makefig.c check.c input_intevals.c input_reg.c\
	 output_region.c readins.c transform_segment.c input_segment.c\
	 prt_Header.c prt_Macro.c prt_Text.c prt_Trailer.c prt_line.c\
	 readreputer.c g_band.c readstring.c char2int.c random.c
OBJS11 = makefig.o check.o input_intevals.o input_reg.o\
	 output_region.o readins.o transform_segment.o input_segment.o\
	 prt_Header.o prt_Macro.o prt_Text.o prt_Trailer.o prt_line.o\
	 readreputer.o g_band.o readstring.o char2int.o random.o

SRCS12 = insencode.c readins.c readpar.c random.c char2int.c\
	 check.c readseq1by1.c
OBJS12 = insencode.o readins.o readpar.o random.o char2int.o\
	 check.o readseq1by1.o

SRCS13 = maketxt.c check.c input_intevals.c input_reg.c\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c
OBJS13 = maketxt.o check.o input_intevals.o input_reg.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o

SRCS30 = reputer2aln.c readreputer.c readpar.c random.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c
OBJS30 = reputer2aln.o readreputer.o readpar.o random.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o

SRCS31 = case2aln.c readcase.c readreputer.c readpar.c random.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c parsestr.c
OBJS31 = case2aln.o readcase.o readreputer.o readpar.o random.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o parsestr.o

SRCS40 = ph2aln.c readph.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c
OBJS40 = ph2aln.o readph.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o

SRCS41 = string2aln.c readstring.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c
OBJS41 = string2aln.o readstring.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o

SRCS42 = string2seq.c readstring.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c trans_loc.c\
	 readclass.c
OBJS42 = string2seq.o readstring.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o trans_loc.o\
	 readclass.o

SRCS43 = classifyaln.c readstring.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c readintv.c transform_len.c
OBJS43 = classifyaln.o readstring.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o readintv.o transform_len.o

SRCS44 = rem_dup.c readstring.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c readintv.c transform_len.c
OBJS44 = rem_dup.o readstring.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o readintv.o transform_len.o

SRCS46 = rem_hetero.c readstring.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c readintv.c transform_len.c
OBJS46 = rem_hetero.o readstring.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o readintv.o transform_len.o

SRCS47 = grabaln.c readstring.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c readintv.c transform_len.c
OBJS47 = grabaln.o readstring.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o readintv.o transform_len.o

SRCS23 = free_align.c makedge.c readseq1by1.c read_graph.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c simplifygraph.c readpar.c rem_cycle.c\
	erasenext.c initialize.c readclass.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c
OBJS23 = free_align.o makedge.o readseq1by1.o read_graph.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o simplifygraph.o readpar.o rem_cycle.o\
	erasenext.o initialize.o readclass.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o

SRCS24 = free_align.c makedge.c readseq1by1.c read_graph.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c simplifygraph_new.c readpar.c rem_cycle.c\
	erasenext.c initialize.c readclass.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c\
	add_int_edge.c create_impedges.c sort_edges.c
OBJS24 = free_align.o makedge.o readseq1by1.o read_graph.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o simplifygraph_new.o readpar.o rem_cycle.o\
	erasenext.o initialize.o readclass.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o\
	add_int_edge.o create_impedges.o sort_edges.o

SRCS26 = free_align.c makedge.c readseq1by1.c read_graph.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c simplifygraph_new_len.c readpar.c rem_cycle.c\
	erasenext.c initialize.c readclass.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c\
	add_int_edge.c create_impedges.c sort_edges.c\
	readstring.c readreputer.c g_band.c
OBJS26 = free_align.o makedge.o readseq1by1.o read_graph.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o simplifygraph_new_len.o readpar.o rem_cycle.o\
	erasenext.o initialize.o readclass.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o\
	add_int_edge.o create_impedges.o sort_edges.o\
	readstring.o readreputer.o g_band.o

SRCS48 = prepare_aln.c check.c input_intevals.c input_reg.c outputmatrix.o\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c\
	 readintv.c input_segment.c common_regions.c getalignment.c\
	 copyseq.c getseq.c NJtree.c kimura2D.c readseq1by1.c
OBJS48 = prepare_aln.o check.o input_intevals.o input_reg.o outputmatrix.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o\
	 readintv.o input_segment.o common_regions.o getalignment.o\
	 copyseq.o getseq.o NJtree.o kimura2D.o readseq1by1.o

SRCS49 = put_single.c check.c input_intevals.c input_reg.c\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c\
	 readintv.c input_segment.c common_regions.c getalignment.c
OBJS49 = put_single.o check.o input_intevals.o input_reg.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o\
	 readintv.o input_segment.o common_regions.o getalignment.o

SRCS50 = perform_aln.c align2seq.c getseq.c check.c input_intevals.c input_reg.c\
	 readins.c transform_segment.c readstring.c readreputer.c llmax0.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c readseq1by1.c\
	 readintv.c input_segment.c common_regions.c getalignment.c
OBJS50 = perform_aln.o align2seq.o getseq.o check.o input_intevals.o input_reg.o\
	 readins.o transform_segment.o readstring.o readreputer.o llmax0.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o readseq1by1.o\
	 readintv.o input_segment.o common_regions.o getalignment.o

SRCS51 = count_rep.c check.c input_intevals.c input_reg.c outputmatrix.o\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c\
	 readintv.c input_segment.c common_regions.c getalignment.c\
	 copyseq.c getseq.c NJtree.c kimura2D.c readseq1by1.c
OBJS51 = count_rep.o check.o input_intevals.o input_reg.o outputmatrix.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o\
	 readintv.o input_segment.o common_regions.o getalignment.o\
	 copyseq.o getseq.o NJtree.o kimura2D.o readseq1by1.o

SRCS52 = countall.c check.c
OBJS52 = countall.o check.o

SRCS53 = cutseq.c check.c input_intevals.c input_reg.c\
	 output_region.c readins.c transform_segment.c input_segment.c\
	 prt_Header.c prt_Macro.c prt_Text.c prt_Trailer.c prt_line.c\
	 readreputer.c g_band.c readstring.c char2int.c random.c\
	 output_contig.c getseq.c write_graph.c readseq1by1.c
OBJS53 = cutseq.o check.o input_intevals.o input_reg.o\
	 output_region.o readins.o transform_segment.o input_segment.o\
	 prt_Header.o prt_Macro.o prt_Text.o prt_Trailer.o prt_line.o\
	 readreputer.o g_band.o readstring.o char2int.o random.o\
	 output_contig.o getseq.o write_graph.o readseq1by1.o

SRCS54 = makechrfig.c check.c input_intevals.c input_reg.c\
	 output_region.c readins.c transform_segment.c input_segment.c\
	 prt_Header.c prt_Macro.c prt_Text.c prt_Trailer.c prt_line.c\
	 readreputer.c g_band.c readstring.c char2int.c random.c
OBJS54 = makechrfig.o check.o input_intevals.o input_reg.o\
	 output_region.o readins.o transform_segment.o input_segment.o\
	 prt_Header.o prt_Macro.o prt_Text.o prt_Trailer.o prt_line.o\
	 readreputer.o g_band.o readstring.o char2int.o random.o

SRCS55 = makechrrepg.c check.c input_intevals.c input_reg.c\
	 output_region.c readins.c transform_segment.c input_segment.c\
	 prt_Header.c prt_Macro.c prt_Text.c prt_Trailer.c prt_line.c\
	 readreputer.c g_band.c readstring.c char2int.c random.c
OBJS55 = makechrrepg.o check.o input_intevals.o input_reg.o\
	 output_region.o readins.o transform_segment.o input_segment.o\
	 prt_Header.o prt_Macro.o prt_Text.o prt_Trailer.o prt_line.o\
	 readreputer.o g_band.o readstring.o char2int.o random.o

SRCS56 = classifyaln_seg.c readstring.c readpar.c random.c readreputer.c output_align.c\
	 check.c free_align.c g_band.c char2int.c readseq1by1.c readintv.c transform_len.c
OBJS56 = classifyaln_seg.o readstring.o readpar.o random.o readreputer.o output_align.o\
	 check.o free_align.o g_band.o char2int.o readseq1by1.o readintv.o transform_len.o

SRCS57 = segment_cons.c check.c input_intevals.c input_reg.c outputmatrix.o\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c\
	 readintv.c input_segment.c common_regions.c getalignment.c\
	 copyseq.c getseq.c NJtree.c kimura2D.c readseq1by1.c\
	 buildcons.c
OBJS57 = segment_cons.o check.o input_intevals.o input_reg.o outputmatrix.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o\
	 readintv.o input_segment.o common_regions.o getalignment.o\
	 copyseq.o getseq.o NJtree.o kimura2D.o readseq1by1.o\
	 buildcons.o

SRCS58 = def_ancdup.c check.c input_intevals.c input_reg.c\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c\
	 readintv.c input_segment.c simulate_pair.c count_comp.c
OBJS58 = def_ancdup.o check.o input_intevals.o input_reg.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o\
	 readintv.o input_segment.o simulate_pair.o count_comp.o

SRCS59 = loc_core.c check.c input_intevals.c input_reg.c outputmatrix.o\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c\
	 readintv.c input_segment.c common_regions.c getalignment.c\
	 copyseq.c getseq.c NJtree.c kimura2D.c readseq1by1.c\
	 buildcons.c
OBJS59 = loc_core.o check.o input_intevals.o input_reg.o outputmatrix.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o\
	 readintv.o input_segment.o common_regions.o getalignment.o\
	 copyseq.o getseq.o NJtree.o kimura2D.o readseq1by1.o\
	 buildcons.o

SRCS60 = free_align.c makedge.c readseq1by1.c read_graph.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c simplifygraph_new_new.c readpar.c rem_cycle.c\
	erasenext.c initialize.c readclass.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c\
	add_int_edge.c create_impedges.c sort_edges.c\
	readstring.c readreputer.c g_band.c
OBJS60 = free_align.o makedge.o readseq1by1.o read_graph.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o simplifygraph_new_new.o readpar.o rem_cycle.o\
	erasenext.o initialize.o readclass.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o\
	add_int_edge.o create_impedges.o sort_edges.o\
	readstring.o readreputer.o g_band.o

SRCS61 = free_align.c makedge.c readseq1by1.c read_graph.c\
	count_vertex.c free_class.c merge.c shave_graph.c\
	countnodes.c free_graph.c output_graph.c interval.c\
	eraseedge.c graph.c simplifygraph_new_len_new.c readpar.c rem_cycle.c\
	erasenext.c initialize.c readclass.c check.c\
	char2int.c random.c count_edge.c insert_edge.c\
	readpath.c width.c write_graph.c rem_short_edge.c\
	output_contig.c initialize_edge.c output_align.c\
	add_int_edge.c create_impedges.c sort_edges.c\
	readstring.c readreputer.c g_band.c
OBJS61 = free_align.o makedge.o readseq1by1.o read_graph.o\
	count_vertex.o free_class.o merge.o shave_graph.o\
	countnodes.o free_graph.o output_graph.o interval.o\
	eraseedge.o graph.o simplifygraph_new_len_new.o readpar.o rem_cycle.o\
	erasenext.o initialize.o readclass.o check.o\
	char2int.o random.o count_edge.o insert_edge.o\
	readpath.o width.o write_graph.o rem_short_edge.o\
	output_contig.o initialize_edge.o output_align.o\
	add_int_edge.o create_impedges.o sort_edges.o\
	readstring.o readreputer.o g_band.o

SRCS62 = pair_bp.c check.c input_intevals.c input_reg.c outputmatrix.o\
	 readins.c transform_segment.c readstring.c readreputer.c\
	 g_band.c char2int.c random.c transform_len.c readpar.c\
	 readintv.c input_segment.c common_regions.c getalignment.c\
	 copyseq.c getseq.c NJtree.c kimura2D.c readseq1by1.c\
	 buildcons.c comput_bp.c
OBJS62 = pair_bp.o check.o input_intevals.o input_reg.o outputmatrix.o\
	 readins.o transform_segment.o readstring.o readreputer.o\
	 g_band.o char2int.o random.o transform_len.o readpar.o\
	 readintv.o input_segment.o common_regions.o getalignment.o\
	 copyseq.o getseq.o NJtree.o kimura2D.o readseq1by1.o\
	 buildcons.o comput_bp.o

.c.o :
	$(CC) $(CFLAGS) -c $<

repeat_sin_read: $(OBJS22)
	$(CC) $(CCOPT) -o repeat_sin_read $(OBJS22) $(LIBS)

repeat_sin: $(OBJS21)
	$(CC) $(CCOPT) -o repeat_sin $(OBJS21) $(LIBS)

repeat_sin_len: $(OBJS25)
	$(CC) $(CCOPT) -o repeat_sin_len $(OBJS25) $(LIBS)

makefig: $(OBJS11)
	$(CC) $(CCOPT) -o makefig $(OBJS11) $(LIBS)

simplifygraph_new: $(OBJS24)
	$(CC) $(CCOPT) -o simplifygraph_new $(OBJS24) $(LIBS)

simplifygraph_new_len: $(OBJS26)
	$(CC) $(CCOPT) -o simplifygraph_new_len $(OBJS26) $(LIBS)

simplifygraph: $(OBJS23)
	$(CC) $(CCOPT) -o simplifygraph $(OBJS23) $(LIBS)

bl2aln: $(OBJS20)
	$(CC) $(CCOPT) -o bl2aln $(OBJS20) $(LIBS)

case2aln: $(OBJS31)
	$(CC) $(CCOPT) -o case2aln $(OBJS31) $(LIBS)

longencode: $(OBJS10)
	$(CC) $(CCOPT) -o longencode $(OBJS10) $(LIBS)

insencode: $(OBJS12)
	$(CC) $(CCOPT) -o insencode $(OBJS12) $(LIBS)

maketxt: $(OBJS13)
	$(CC) $(CCOPT) -o maketxt $(OBJS13) $(LIBS)

reputer2aln: $(OBJS30)
	$(CC) $(CCOPT) -o reputer2aln $(OBJS30) $(LIBS)

ph2aln: $(OBJS40)
	$(CC) $(CCOPT) -o ph2aln $(OBJS40) $(LIBS)

string2aln: $(OBJS41)
	$(CC) $(CCOPT) -o string2aln $(OBJS41) $(LIBS)

string2seq: $(OBJS42)
	$(CC) $(CCOPT) -o string2seq $(OBJS42) $(LIBS)

classifyaln: $(OBJS43)
	$(CC) $(CCOPT) -o classifyaln $(OBJS43) $(LIBS)

rem_dup: $(OBJS44)
	$(CC) $(CCOPT) -o rem_dup $(OBJS44) $(LIBS)

rem_hetero: $(OBJS46)
	$(CC) $(CCOPT) -o rem_hetero $(OBJS46) $(LIBS)

grabaln: $(OBJS47)
	$(CC) $(CCOPT) -o grabaln $(OBJS47) $(LIBS)

prepare_aln: $(OBJS48)
	$(CC) $(CCOPT) -o prepare_aln $(OBJS48) $(LIBS)

put_single: $(OBJS49)
	$(CC) $(CCOPT) -o put_single $(OBJS49) $(LIBS)

perform_aln: $(OBJS50)
	$(CC) $(CCOPT) -o perform_aln $(OBJS50) $(LIBS)

count_rep: $(OBJS51)
	$(CC) $(CCOPT) -o count_rep $(OBJS51) $(LIBS)

countall: $(OBJS52)
	$(CC) $(CCOPT) -o countall $(OBJS52) $(LIBS)

cutseq: $(OBJS53)
	$(CC) $(CCOPT) -o cutseq $(OBJS53) $(LIBS)

makechrfig: $(OBJS54)
	$(CC) $(CCOPT) -o makechrfig $(OBJS54) $(LIBS)

makechrrepg: $(OBJS55)
	$(CC) $(CCOPT) -o makechrrepg $(OBJS55) $(LIBS)

classifyaln_seg: $(OBJS56)
	$(CC) $(CCOPT) -o classifyaln_seg $(OBJS56) $(LIBS)

segment_cons: $(OBJS57)
	$(CC) $(CCOPT) -o segment_cons $(OBJS57) $(LIBS)

def_ancdup: $(OBJS58)
	$(CC) $(CCOPT) -o def_ancdup $(OBJS58) $(LIBS)

loc_core: $(OBJS59)
	$(CC) $(CCOPT) -o loc_core $(OBJS59) $(LIBS)

simplifygraph_new_new: $(OBJS60)
	$(CC) $(CCOPT) -o simplifygraph_new_new $(OBJS60) $(LIBS)

simplifygraph_new_len_new: $(OBJS61)
	$(CC) $(CCOPT) -o simplifygraph_new_len_new $(OBJS61) $(LIBS)

pair_bp: $(OBJS62)
	$(CC) $(CCOPT) -o pair_bp $(OBJS62) $(LIBS)

new :
	touch *.c

install: all
	mkdir $(bindir)
#	owen changed line above. Was "mkdirhier $(bindir)"
#	$(top_srcdir)/mkinstalldirs $(bindir)
#	$(top_srcdir)/mkinstalldirs $(libdir)
	for prog in ${PROGRAMS}; do \
		mv $$prog $(bindir)/. ; \
	done

uninstall:
	for prog in ${PROGRAMS}; do \
		rm -f $(bindir)/${prog} ${prog}\
	done && test -z "$$fail"

# removes whatever can be built with make except xypost
clean:
	/bin/rm -rf *.o bin/ 
	for prog in ${PROGRAMS} ; do \
		rm -f $$prog ; \
	done

distclean: clean
	rm -f Makefile config.h config.status config.cache config.log
